package com.accesses.administrative_system.entity.enums;

public enum AlertType {

    TRY_SEND_MESSAGE,
    MESSAGE_SEND_SUCCESSFUL,
    MESSAGE_SEND_FAILURE,

    TRY_CONNECT_DRIVE,
    CONNECT_DRIVER_SUCCESSFUL,
    CONNECT_DRIVER_FAILURE,

    TRY_DISCONNECT_DRIVE,
    DISCONNECT_DRIVER_SUCCESSFUL,
    DISCONNECT_DRIVER_FAILURE,

    TRY_WHATSAPP_OPEN_WINDOW,
    WHATSAPP_OPEN_WINDOW_SUCCESSFUL,
    WHATSAPP_OPEN_WINDOW_FAILURE,

    TRY_WHATSAPP_CLOSE_WINDOW,
    WHATSAPP_CLOSE_WINDOW_SUCCESSFUL,
    WHATSAPP_CLOSE_WINDOW_FAILURE,

    TRY_LOGIN_WHATSAPP,
    LOGIN_WHATSAPP_SUCCESSFUL,
    LOGIN_WHATSAPP_FAILURE,


}
